version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: global_technology_frontend
    volumes:
      - shared_storage:/usr/share/nginx/html/storage
    ports:
      - "8080:8080"
    depends_on:
      - api
  
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile

    container_name: global_technology_frontend_dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - shared_storage:/app/public/storage
    ports:
      - "8081:8080"
    depends_on:
      - api
    command: npm run serve -- --public 0.0.0.0:8080

  api:
    build: ./api
    container_name: global_technology_api
    volumes:
      - ./api:/app
      - shared_storage:/app/storage
    ports:
      - 80:80
    environment:
      - TOKEN_SECRET=$TOKEN_SECRET
      - DB_HOST=database
      - DB_USER=$MYSQL_ROOT_USER
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=3307
    depends_on:
      - database
          
  phpmyadmin:
    image: phpmyadmin
    container_name: global_technology_phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - 40001:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database

  database:
    image: mariadb:10.10.2
    container_name: global_technology_database
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - ./database/global_technology.sql:/docker-entrypoint-initdb.d/global_technology.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
  frontend_node_modules:
  shared_storage: